MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom.urlsafe_base64
    end

    def reset_session_token
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    attr_reader :password
    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        password_obj = BCrypt::Password.new(self.password_digest)
        password_obj.is_password?(password)
    end

    def self.find_by_creditials(email, password)
        @user = User.find_by(email: email)
        
        if @user && @user.is_password?(password)
            @user
        else
            nil
        end
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
        # debugger
    end

    def login(user)
        session[:session_token] = user.reset_session_token
    end

    def logged_in?
        !!current_user
        debugger
    end

    def logout
        current_user.reset_session_token if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    #login form for the user
    def new
        @user = User.new
        render :new
    end

    #checks to see if login was successful
    def create
        @user = User.find_by_creditials(params[:user][:email], params[:user][:password])

        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def destroy
        name = @current_user.email
        logout
        redirect_to new_session_url
    end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        render :show
    end
    
    def new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            render :new
        end

    end

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <%debugger%>
    <% if logged_in? %>
      <h5>hello, <%= current_user.email%>
      <form action="session_url" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="logout">
      </form>
    <% else %>
      <a href="<%= new_user_url%>">Sign Up</a>
      <a href="<%= new_session_url%>">Login</a>
    <% end %>
  </header>

  <body>
    <%= yield %>
  </body>

</html>

MusicApp/app/views/users/new.html.erb
<h2>User Sign Up Page</h2>

<form action="<%= users_url %>" method="post">

    <label>Email:
        <input type="text" name="user[email]">
    </label>

    <br/>
    
    <label>Password:
        <input type="password" name="user[password]">
    </label>

    <br>
    <input type="submit" value="Create User">
</form>

MusicApp/app/views/users/show.html.erb
<h2>User Show Page</h2>
<p><%= @user.email %></p>